import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { Pool } from "pg";
import dotenv from "dotenv";
import sharp from "sharp";
import express from "express";
import jwt from "jsonwebtoken";
dotenv.config();
dotenv.config({path:"backend/.env"});

async function main() {
  const url=process.env.STAGING_DATABASE_URL;
  if(!url)throw new Error("Configure STAGING_DATABASE_URL.");
  const schema=`smoke_content_${Date.now()}`;
  const temp=await fs.mkdtemp(path.join(os.tmpdir(),"ediretor-content-"));
  const admin=new Pool({connectionString:url,max:1});
  let pool:Pool|undefined;
  let server:ReturnType<ReturnType<typeof express>["listen"]>|undefined;
  try {
    await admin.query(`CREATE SCHEMA "${schema}"`);
    const isolated=new URL(url);isolated.searchParams.set("options",`-c search_path=${schema}`);
    process.env.DATABASE_URL=isolated.toString();process.env.UPLOAD_FILES_DIR=temp;process.env.GENERATED_FILES_DIR=temp;
    process.env.OPENAI_API_KEY="";process.env.JWT_SECRET="content-smoke-secret-at-least-32-characters";
    process.env.ADMIN_NAME="";process.env.ADMIN_EMAIL="";process.env.ADMIN_PASSWORD="";
    const db=await import("../db/connection.js");pool=db.pool;
    const {migrate}=await import("../db/migrate.js");await migrate();await db.validateTenantRole();
    console.log("Estrutura temporária e isolamento validados.");
    const library=await import("../services/visualLibraryService.js");
    const editorial=await import("../services/editorialService.js");
    const calendar=await import("../services/editorialCalendar.js");
    const clients=await import("../services/clientService.js");
    const orgA=Number((await db.get<{id:number}>("SELECT id FROM organizations ORDER BY id LIMIT 1"))!.id);
    const orgB=Number((await db.run("INSERT INTO organizations(name,slug) VALUES('Segunda empresa','segunda')")).lastInsertRowid);
    let clientId=0,otherClientId=0,subjectId=0,planId=0,photo="",contentId=0;
    const today=calendar.localDate(new Date(),"America/Sao_Paulo");
    const selection=library.visualSelectionSchema.parse({products:"auto",mode:"composition"});
    await db.runWithOrganizationContext(orgA,async()=>{
      const client=await clients.createClient({name:"Marca teste",country:"Brasil",state:"SP",city:"Campinas",anniversary_date:today.slice(5),time_zone:"America/Sao_Paulo",founding_year:"2010"});
      clientId=Number(client!.id);otherClientId=Number((await clients.createClient({name:"Outro cliente"}))!.id);
      assert.equal(client!.city,"Campinas");
      subjectId=(await library.saveSubject(clientId,null,{kind:"product",name:"Produto real",approved:true,allow_ads:true,allow_social:true})).id;
      const fixture=path.join(temp,"fixture.png");await sharp({create:{width:512,height:512,channels:4,background:"#ee9922"}}).png().toFile(fixture);
      await library.addPhoto(clientId,subjectId,fixture,"Frente");
      const resolved=await library.resolveVisuals(clientId,selection,"social");assert.equal(resolved.length,1);photo=resolved[0].filename;
      await assert.rejects(()=>library.resolveVisuals(otherClientId,library.visualSelectionSchema.parse({products:"manual",product_ids:[subjectId]}),"ads"));
      planId=(await editorial.saveEditorialPlan({client_id:clientId,name:"Semanal",active:true,automatic:false,posts_per_week:2,pillars:["Educação","Comunidade"],formats:["post"],weekly_image_limit:2,visual_selection:selection})).id;
      let searches=0;
      const research=async()=>{searches++;return [];};
      const [one,two]=await Promise.all([editorial.createEditorialBatch(planId,undefined,research),editorial.createEditorialBatch(planId,undefined,research)]);
      assert.equal(one!.id,two!.id);assert.equal(searches,1);
      const list=await editorial.getEditorialCalendar(planId);assert.equal(list.contents.length,2);
      assert.ok(list.contents.some(c=>String(c.topic).includes("Aniversário")));
      contentId=Number(list.contents[0].id);await editorial.contentAction(contentId,"generate");
    });
    console.log("Biblioteca, aniversário e planejamento concorrente validados.");
    await db.runWithOrganizationContext(orgB,async()=>{
      assert.equal((await db.all("SELECT id FROM visual_subjects")).length,0);
      assert.equal((await db.all("SELECT id FROM social_contents")).length,0);
      await assert.rejects(()=>editorial.getEditorialCalendar(planId));
      await assert.rejects(()=>library.listSubjects(clientId));
      await assert.rejects(()=>db.run("INSERT INTO visual_photos(client_id,subject_id,filename) VALUES(?,?,?)",[clientId,subjectId,"invalid.png"]));
    });
    const {requireAuth}=await import("../middleware/authMiddleware.js");
    const {requireOrganization}=await import("../middleware/organizationMiddleware.js");
    const {contentRoutes}=await import("../routes/contentRoutes.js");
    const {uploadedMediaController}=await import("../controllers/mediaController.js");
    const {asyncHandler}=await import("../utils/asyncHandler.js");
    const {errorHandler}=await import("../utils/errors.js");
    const userId=Number((await db.run("INSERT INTO users(name,email,password_hash,role,active) VALUES('Membro','member@test.invalid','unused','user',TRUE)")).lastInsertRowid);
    await db.run("INSERT INTO organization_members(organization_id,user_id,role,status) VALUES(?,?,'member','active')",[orgA,userId]);
    const token=jwt.sign({organizationId:orgA},process.env.JWT_SECRET,{subject:String(userId),issuer:"e-criativo",audience:"e-criativo-web",expiresIn:60});
    const app=express();app.use(express.json());app.use("/api",requireAuth,requireOrganization,contentRoutes);app.get("/uploads/:filename",requireAuth,requireOrganization,asyncHandler(uploadedMediaController));app.use(errorHandler);
    server=app.listen(0,"127.0.0.1");await new Promise<void>(resolve=>server!.once("listening",resolve));
    const address=server.address() as {port:number};const base=`http://127.0.0.1:${address.port}`;
    assert.equal((await fetch(`${base}/api/social-media/plans`,{headers:{Authorization:`Bearer ${token}`}})).status,403);
    assert.equal((await fetch(`${base}/uploads/${photo}`)).status,401);
    assert.equal((await fetch(`${base}/uploads/${photo}`,{headers:{Authorization:`Bearer ${token}`}})).status,200);
    console.log("Acesso HTTP e mídia privada validados.");
    let generations=0;
    await editorial.processEditorialQueue({research:async()=>[],write:async()=>({caption:"Legenda teste",alt_text:"Produto",image_prompts:["Produto em fundo limpo"]}),image:async()=>{generations++;return {imagePath:path.join(temp,"result.png"),imageUrl:"https://test.invalid/generated/result.png",aiUsageLogId:1};}});
    await editorial.processEditorialQueue({research:async()=>[],write:async()=>{throw new Error("Não deveria repetir");},image:async()=>{throw new Error("Não deveria repetir");}});
    assert.equal(generations,1);
    await db.runWithOrganizationContext(orgA,async()=>{
      const item=await db.get<{status:string}>("SELECT status FROM social_contents WHERE id=?",[contentId]);assert.equal(item!.status,"review");
      await editorial.contentAction(contentId,"approve");
      await assert.rejects(()=>editorial.contentAction(contentId,"generate"));
      await editorial.contentAction(contentId,"reject","Ajustar a composição");
      await editorial.contentAction(contentId,"regenerate","Usar fundo claro");
      const version=await db.get<{revisions:unknown[];status:string}>("SELECT revisions,status FROM social_contents WHERE id=?",[contentId]);
      assert.equal(version!.revisions.length,1);assert.equal(version!.status,"pending");
      const refs=await library.resolveVisuals(clientId,selection,"social");
      await library.saveSubject(clientId,subjectId,{kind:"product",name:"Produto real",approved:true,allow_ads:true,allow_social:true,active:false});
      await assert.rejects(()=>library.resolveVisuals(clientId,selection,"social"));
      await assert.rejects(()=>library.validateVisualReferences(clientId,refs,"social"));
    });
    console.log(JSON.stringify({status:"ok",checks:["localização e aniversário","biblioteca e imagens privadas","isolamento empresa e cliente","revogação de material","lote semanal idempotente","produção e aprovação","permissões HTTP"]}));
  } finally {
    if(server)await new Promise<void>(resolve=>server!.close(()=>resolve()));
    if(pool)await pool.end();
    await admin.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);await admin.end();
    await fs.rm(temp,{recursive:true,force:true});
  }
}
void main().catch(error=>{console.error(error instanceof Error?error.message:error);process.exitCode=1;});
